### PR TITLE
templates: Add opentype feature picker

### PR DESCRIPTION
**Pull request by m4rc1e**
This PR implements an OpenType feature picker in the html views. This feature was requested by @vv-monsalve (great idea btw).

Screenshot 2023-08-02 at 14 55 31

Since the text boxes are also contenteditable, it's becoming a very nice playground to test out custom user text, similar to Impallari's tester.

### CODE REVIEW

**Comment by vv-monsalve** [comment]
Working beautifully! Thanks

**Comment by vv-monsalve** [comment]
Updating the report. It worked perfectly (without reported errors) at the `proof` option. 

However, when using it with the `diff` option, the output folder was created, but it reported two different errors at two different run times:

- Using the `--imgs` option:
    ````
    ValueError: height and width must be > 0
    [2/2] _diffbrowsers diff -fb "/Users/v... ".*" --imgs --filter-styles "Regular"
    ninja: build stopped: subcommand failed.
    ````

- Without using `--imgs` option
    ````
    ValueError: height and width must be > 0
    ninja: build stopped: subcommand failed.
    ````

I'm attaching here a .zip file that includes

- The output folder (which includes the fonts to replicate the test)
- A `.txt` file where I copy/paste **both** full tracebacks.

[qaPraise-L-01-diffOT.zip](https://github.com/googlefonts/diffenator2/files/12242674/qaPraise-L-01-diffOT.zip)

**Comment by m4rc1e** [comment]
Thanks, I think this is related to #82 instead. i'll roll a fix now.

**Comment by vv-monsalve** [comment]
> i'll roll a fix now.

Could the OT picker include the positional alternates (fina, init) like [this one (second image)](https://github.com/googlefonts/praise-script/issues/14#issuecomment-1659433335)?

Posting it here since you'll work on the fix. Let me know if you prefer to track this in a new issue, and I'll open one.

**Pull request merged**
