### PR TITLE
Build TTJ table in Javascript

### PR DESCRIPTION
**Pull request by simoncozens**
Requires jquery, which it loads from a CDN. On a Noto Sans Arabic report, reduced the file size from 800k to 120k.

### CODE REVIEW

**Comment by m4rc1e** [comment]
Cool! only gripe is jquery. Can we make it vanilla instead.

**Comment by simoncozens** [comment]
I *could* do, but it would be a lot more yucky. What problem are we trying to solve?

**Comment by davelab6** [comment]
JQuery from CDN is fine with me. The only gripe I have is a table being constructed with div/span instead of real table elements ;)

**Comment by m4rc1e** [comment]
I'll happily accept the jquery for now.

We have a slight issue, Python's json serialiser doesn't like tuples.

```
TypeError: keys must be str, int, float, bool or None, not tuple
ninja: build stopped: subcommand failed.
```

I can happily fix this. I'll chuck it on the queue.

**Comment by m4rc1e** [comment]
Thank you Simon! a certain project is 90% smaller in size so this is a massive win.

**Pull request merged**
